-- MySQL Script generated by MySQL Workbench
-- Sat Aug 22 11:20:56 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema exercicio1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercicio1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercicio1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `exercicio1` ;

-- -----------------------------------------------------
-- Table `exercicio1`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio1`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `exercicio1`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio1`.`fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idfornecedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `exercicio1`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio1`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `valor` INT NULL DEFAULT NULL,
  `codigo.fornecedor` INT NULL DEFAULT NULL,
  `codigo.categoria` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_produto_fornecedor_idx` (`codigo.fornecedor` ASC) VISIBLE,
  INDEX `fk_produto_categoria_idx` (`codigo.categoria` ASC) VISIBLE,
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`codigo.categoria`)
    REFERENCES `exercicio1`.`categoria` (`idcategoria`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_produto_fornecedor`
    FOREIGN KEY (`codigo.fornecedor`)
    REFERENCES `exercicio1`.`fornecedor` (`idfornecedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
